name: AWS CDK Deploy

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install AWS CLI
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Deploy AWS CDK
        run: |
          npm install
          npx ts-node bin/main_stack.ts 
          # npx cdk deploy --require-approval never --app 'node bin/main_stack.js'
        env:
          AWS_DEFAULT_REGION: "us-east-2" # Replace with your preferred region

      - name: Merge Pull Request
        if: success()
        run: |
          # Merge the pull request using the GitHub API
          PR_NUMBER=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH")
          GITHUB_TOKEN="$PR_GITHUB_TOKEN"
          
          # Merge the pull request
          curl -X PUT "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}/merge" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -d '{"commit_title": "Auto Merge", "merge_method": "squash"}'
